// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: prober/prober.proto

package prober

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message
type ProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_prober_prober_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prober_prober_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_prober_prober_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the result
type ProbeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatencyMsecs  float32                `protobuf:"fixed32,1,opt,name=latency_msecs,json=latencyMsecs,proto3" json:"latency_msecs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeReply) Reset() {
	*x = ProbeReply{}
	mi := &file_prober_prober_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeReply) ProtoMessage() {}

func (x *ProbeReply) ProtoReflect() protoreflect.Message {
	mi := &file_prober_prober_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeReply.ProtoReflect.Descriptor instead.
func (*ProbeReply) Descriptor() ([]byte, []int) {
	return file_prober_prober_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeReply) GetLatencyMsecs() float32 {
	if x != nil {
		return x.LatencyMsecs
	}
	return 0
}

var File_prober_prober_proto protoreflect.FileDescriptor

const file_prober_prober_proto_rawDesc = "" +
	"\n" +
	"\x13prober/prober.proto\x12\x06prober\"\"\n" +
	"\fProbeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\n" +
	"ProbeReply\x12#\n" +
	"\rlatency_msecs\x18\x01 \x01(\x02R\flatencyMsecs2G\n" +
	"\rProberService\x126\n" +
	"\bDoProbes\x12\x14.prober.ProbeRequest\x1a\x12.prober.ProbeReply\"\x00B\n" +
	"Z\b./proberb\x06proto3"

var (
	file_prober_prober_proto_rawDescOnce sync.Once
	file_prober_prober_proto_rawDescData []byte
)

func file_prober_prober_proto_rawDescGZIP() []byte {
	file_prober_prober_proto_rawDescOnce.Do(func() {
		file_prober_prober_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prober_prober_proto_rawDesc), len(file_prober_prober_proto_rawDesc)))
	})
	return file_prober_prober_proto_rawDescData
}

var file_prober_prober_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prober_prober_proto_goTypes = []any{
	(*ProbeRequest)(nil), // 0: prober.ProbeRequest
	(*ProbeReply)(nil),   // 1: prober.ProbeReply
}
var file_prober_prober_proto_depIdxs = []int32{
	0, // 0: prober.ProberService.DoProbes:input_type -> prober.ProbeRequest
	1, // 1: prober.ProberService.DoProbes:output_type -> prober.ProbeReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prober_prober_proto_init() }
func file_prober_prober_proto_init() {
	if File_prober_prober_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prober_prober_proto_rawDesc), len(file_prober_prober_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prober_prober_proto_goTypes,
		DependencyIndexes: file_prober_prober_proto_depIdxs,
		MessageInfos:      file_prober_prober_proto_msgTypes,
	}.Build()
	File_prober_prober_proto = out.File
	file_prober_prober_proto_goTypes = nil
	file_prober_prober_proto_depIdxs = nil
}
