// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: prober/prober.proto

package prober

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProberService_DoProbes_FullMethodName = "/prober.ProberService/DoProbes"
)

// ProberServiceClient is the client API for ProberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The probe service definition
type ProberServiceClient interface {
	DoProbes(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeReply, error)
}

type proberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProberServiceClient(cc grpc.ClientConnInterface) ProberServiceClient {
	return &proberServiceClient{cc}
}

func (c *proberServiceClient) DoProbes(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeReply)
	err := c.cc.Invoke(ctx, ProberService_DoProbes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProberServiceServer is the server API for ProberService service.
// All implementations must embed UnimplementedProberServiceServer
// for forward compatibility.
//
// The probe service definition
type ProberServiceServer interface {
	DoProbes(context.Context, *ProbeRequest) (*ProbeReply, error)
	mustEmbedUnimplementedProberServiceServer()
}

// UnimplementedProberServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProberServiceServer struct{}

func (UnimplementedProberServiceServer) DoProbes(context.Context, *ProbeRequest) (*ProbeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoProbes not implemented")
}
func (UnimplementedProberServiceServer) mustEmbedUnimplementedProberServiceServer() {}
func (UnimplementedProberServiceServer) testEmbeddedByValue()                       {}

// UnsafeProberServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProberServiceServer will
// result in compilation errors.
type UnsafeProberServiceServer interface {
	mustEmbedUnimplementedProberServiceServer()
}

func RegisterProberServiceServer(s grpc.ServiceRegistrar, srv ProberServiceServer) {
	// If the following call pancis, it indicates UnimplementedProberServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProberService_ServiceDesc, srv)
}

func _ProberService_DoProbes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProberServiceServer).DoProbes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProberService_DoProbes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProberServiceServer).DoProbes(ctx, req.(*ProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProberService_ServiceDesc is the grpc.ServiceDesc for ProberService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProberService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prober.ProberService",
	HandlerType: (*ProberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoProbes",
			Handler:    _ProberService_DoProbes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prober/prober.proto",
}
